name: Stockthenature
favicon: null
layout_spectrum: 0.24758
typography_spectrum: 0.04717089980840683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f2427'
    - '#c2bbab'
    - '#706f75'
    - '#efd6ae'
    - '#000106'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
